// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	models "github.com/ad3n/resto/models"
	mock "github.com/stretchr/testify/mock"
)

// OrderRepository is an autogenerated mock type for the OrderRepository type
type OrderRepository struct {
	mock.Mock
}

// Find provides a mock function with given fields: Id
func (_m *OrderRepository) Find(Id int) (*models.Order, error) {
	ret := _m.Called(Id)

	var r0 *models.Order
	if rf, ok := ret.Get(0).(func(int) *models.Order); ok {
		r0 = rf(Id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Order)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(Id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Saves provides a mock function with given fields: orders
func (_m *OrderRepository) Saves(orders ...*models.Order) error {
	_va := make([]interface{}, len(orders))
	for _i := range orders {
		_va[_i] = orders[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(...*models.Order) error); ok {
		r0 = rf(orders...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
