// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	models "github.com/ad3n/resto/models"
	mock "github.com/stretchr/testify/mock"
)

// OrderDetailRepository is an autogenerated mock type for the OrderDetailRepository type
type OrderDetailRepository struct {
	mock.Mock
}

// FindByOrder provides a mock function with given fields: order
func (_m *OrderDetailRepository) FindByOrder(order models.Order) ([]models.OrderDetail, error) {
	ret := _m.Called(order)

	var r0 []models.OrderDetail
	if rf, ok := ret.Get(0).(func(models.Order) []models.OrderDetail); ok {
		r0 = rf(order)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.OrderDetail)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(models.Order) error); ok {
		r1 = rf(order)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Saves provides a mock function with given fields: details
func (_m *OrderDetailRepository) Saves(details ...*models.OrderDetail) error {
	_va := make([]interface{}, len(details))
	for _i := range details {
		_va[_i] = details[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(...*models.OrderDetail) error); ok {
		r0 = rf(details...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
