// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	models "github.com/ad3n/resto/models"
	mock "github.com/stretchr/testify/mock"
)

// OrderDetailRepository is an autogenerated mock type for the OrderDetailRepository type
type OrderDetailRepository struct {
	mock.Mock
}

// Find provides a mock function with given fields: Id
func (_m *OrderDetailRepository) Find(Id int) (*models.OrderDetail, error) {
	ret := _m.Called(Id)

	var r0 *models.OrderDetail
	if rf, ok := ret.Get(0).(func(int) *models.OrderDetail); ok {
		r0 = rf(Id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.OrderDetail)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(Id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Saves provides a mock function with given fields: orderDetails
func (_m *OrderDetailRepository) Saves(orderDetails ...*models.OrderDetail) error {
	_va := make([]interface{}, len(orderDetails))
	for _i := range orderDetails {
		_va[_i] = orderDetails[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(...*models.OrderDetail) error); ok {
		r0 = rf(orderDetails...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
